title: 'sean9892 in a vat'
email: sean9892@gmail.com
description: Crypto&PS

baseurl: ''
url: 'http://127.0.0.1:4000/'
timezone: Asia/Seoul 

repository: sean9892/sean9892.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge
 
gems:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: sean9892@gmail.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
#google_analytics:
#  ua: 'UA-158382114-1'
#twitter:
#  username: